export const pagesRoutes = [
  ["v-744ccd44","/src/",{"title":"博客主页"},["/src/README.md"]],
  ["v-7d690631","/src/intro.html",{"title":"介绍页"},[":md"]],
  ["v-cba035f8","/src/links.html",{"title":"博客链接"},[":md"]],
  ["v-6c5c0573","/src/slides.html",{"title":"幻灯片页"},[":md"]],
  ["v-b334c830","/src/demo/",{"title":"文档库"},["/src/demo/README.md"]],
  ["v-7517aed9","/src/demo/disable.html",{"title":"布局与功能禁用"},[":md"]],
  ["v-3ba1c57c","/src/demo/encrypt.html",{"title":"密码加密的文章"},[":md"]],
  ["v-697c033c","/src/demo/markdown.html",{"title":"Markdown 展示"},[":md"]],
  ["v-71832e7c","/src/demo/page.html",{"title":"页面配置"},[":md"]],
  ["v-3f71e594","/src/demo/vuepress.html",{"title":"Vuepress"},[":md"]],
  ["v-f3310c40","/src/posts/cherry.html",{"title":"樱桃"},[":md"]],
  ["v-5a220498","/src/posts/dragonfruit.html",{"title":"火龙果"},[":md"]],
  ["v-5e6699b3","/src/posts/markdown_best_practice.html",{"title":"Markdown 最佳实践"},[":md"]],
  ["v-0521efea","/src/posts/strawberry.html",{"title":"草莓"},[":md"]],
  ["v-2c84ee0f","/src/posts/tomato.html",{"title":"番茄"},[":md"]],
  ["v-54c2c49d","/src/posts/apple/1.html",{"title":"苹果 1"},[":md"]],
  ["v-56779d3c","/src/posts/apple/2.html",{"title":"苹果 2"},[":md"]],
  ["v-582c75db","/src/posts/apple/3.html",{"title":"苹果 3"},[":md"]],
  ["v-59e14e7a","/src/posts/apple/4.html",{"title":"苹果 4"},[":md"]],
  ["v-2e3cf432","/src/posts/banana/1.html",{"title":"香蕉 1"},[":md"]],
  ["v-2ff1ccd1","/src/posts/banana/2.html",{"title":"香蕉 2"},[":md"]],
  ["v-31a6a570","/src/posts/banana/3.html",{"title":"香蕉 3"},[":md"]],
  ["v-335b7e0f","/src/posts/banana/4.html",{"title":"香蕉 4"},[":md"]],
  ["v-45bfa7c8","/src/subjects/ControlEngineering/0-basic_info.html",{"title":"课时零、前置基础"},[":md"]],
  ["v-cb02b920","/src/subjects/ControlEngineering/1-laplace_transfer.html",{"title":"课时一、拉氏变换"},[":md"]],
  ["v-5a92a2fd","/src/subjects/ControlEngineering/2-transfer_function.html",{"title":"课时二、传递函数和数学模型"},[":md"]],
  ["v-151b2df2","/src/subjects/ControlEngineering/3-block_diagram.html",{"title":"课时三、系统方框图及其简化"},[":md"]],
  ["v-3eb448b1","/src/subjects/ControlEngineering/4-time_domain.html",{"title":"课时四、时域瞬态响应分析"},[":md"]],
  ["v-36e0608a","/src/subjects/ControlEngineering/5-error_analyse.html",{"title":"课时五、误差分析和计算"},[":md"]],
  ["v-b594c122","/src/subjects/ControlEngineering/6-frequency_characteristic.html",{"title":"课时六、控制系统的频率特性"},[":md"]],
  ["v-722d1529","/src/subjects/ControlEngineering/7-nyquist.html",{"title":"课时七、Nyquist 图频率特性分析"},[":md"]],
  ["v-5d45e241","/src/subjects/ControlEngineering/8-bode.html",{"title":"课时八、伯德图特性分析"},[":md"]],
  ["v-121a1014","/src/subjects/ControlEngineering/9-routh.html",{"title":"课时九、劳斯稳定性判据"},[":md"]],
  ["v-2bb6f355","/src/subjects/ControlEngineering/",{"title":"机械控制工程基础"},["/src/subjects/ControlEngineering/README.md"]],
  ["v-1ffc6352","/src/subjects/EngineeringTesting/0.html",{"title":"绪论"},[":md"]],
  ["v-1c92b214","/src/subjects/EngineeringTesting/1.html",{"title":"第一章 信号描述与分析基础"},[":md"]],
  ["v-192900d6","/src/subjects/EngineeringTesting/2.html",{"title":"第二章 测试系统的基本特征"},[":md"]],
  ["v-15bf4f98","/src/subjects/EngineeringTesting/3.html",{"title":"第三章 常用传感器工作原理和测量电路"},[":md"]],
  ["v-12559e5a","/src/subjects/EngineeringTesting/4.html",{"title":"第四章 信号的调理与显示记录"},[":md"]],
  ["v-0eebed1c","/src/subjects/EngineeringTesting/5.html",{"title":"第五章 信号分析与处理"},[":md"]],
  ["v-417e6ba4","/src/subjects/EngineeringTesting/",{"title":"工程测试技术"},["/src/subjects/EngineeringTesting/README.md"]],
  ["v-4fb45dce","/src/subjects/EngineeringTesting/test.html",{"title":""},[":md"]],
  ["v-02ef6b66","/src/subjects/MachineryManufacturing/2023test.html",{"title":"2023 年机械制造技术考试复习"},[":md"]],
  ["v-2855e6fb","/src/subjects/MachineryManufacturing/",{"title":"机械制造技术"},["/src/subjects/MachineryManufacturing/README.md"]],
  ["v-fab9e586","/src/subjects/NumericalControl/1-introduction.html",{"title":"第 1 章 绪论"},[":md"]],
  ["v-16ddbdc1","/src/subjects/NumericalControl/2-programming.html",{"title":"第 2 章 数控加工程序的编制"},[":md"]],
  ["v-8cc21dd8","/src/subjects/NumericalControl/3-trajectory_control.html",{"title":"第 3 章 数控技术中的轨迹控制原理"},[":md"]],
  ["v-034ea7e0","/src/subjects/NumericalControl/4-cnc.html",{"title":"第 4 章 计算机数控装置"},[":md"]],
  ["v-530851d1","/src/subjects/NumericalControl/5-fss.html",{"title":"第 5 章 进给伺服系统"},[":md"]],
  ["v-e5761568","/src/subjects/NumericalControl/6-machine_tool.html",{"title":"第 6 章 数控机床总体结构及典型部件"},[":md"]],
  ["v-5e67db66","/src/subjects/NumericalControl/",{"title":"数控技术"},["/src/subjects/NumericalControl/README.md"]],
  ["v-1171b0b0","/src/subjects/ControlEngineering/test/",{"title":"考试相关"},["/src/subjects/ControlEngineering/test/README.md"]],
  ["v-182cbb92","/src/subjects/NumericalControl/test/",{"title":"考试相关"},["/src/subjects/NumericalControl/test/README.md"]],
  ["v-66725974","/src/subjects/ControlEngineering/test/neuq/2023-2024-F.html",{"title":"2023-2024 年秋季考试"},[":md"]],
  ["v-2f052954","/src/subjects/ControlEngineering/test/neuq/",{"title":"东北大学秦皇岛分校"},["/src/subjects/ControlEngineering/test/neuq/README.md"]],
  ["v-4907d817","/src/subjects/NumericalControl/test/neuq/2023-2024-F.html",{"title":"2023-2024 年秋季考试"},[":md"]],
  ["v-2a381fb6","/src/subjects/NumericalControl/test/neuq/",{"title":"东北大学秦皇岛分校"},["/src/subjects/NumericalControl/test/neuq/README.md"]],
  ["v-3706649a","/404.html",{"title":""},[]],
]
